"""Reference trajectory and its state-transition matrix.

This module answers the plan's open question Q12: **where does** :math:`\\Phi`
**come from?**  The whole allocation rests on it -- the coupling matrix
:math:`\\mathbf Q` is generated by nothing else -- and the archive does not
supply it.  The previous campaign integrated the *forced* variational system
:math:`\\delta\\ddot{\\mathbf r}=\\mathbf G\\,\\delta\\mathbf r+\\Delta\\mathbf a`
once per policy and stored the resulting deviation, never the 6x6 matrix.  A
deviation cannot be reused for a different forcing, so the matrix has to be
integrated here.

Cost, stated plainly
--------------------
Carrying :math:`\\Phi` means 36 extra states and one gravity gradient per
right-hand side.  With a central-difference gradient that is six syntheses on
top of the one the trajectory needs, so a variational arc costs roughly seven
times a plain propagation at equal gradient degree -- less if the gradient is
truncated below the reference degree, which is exactly the trade the plan
flags as open (Q13).  Stage M1 is therefore *not* free of integration, and
:func:`estimate_syntheses_per_rhs` exists so that the number entering the
manifest is computed rather than asserted.

Why symplecticity is used rather than a matrix inverse
------------------------------------------------------
The allocation needs the *backward* transport :math:`\\Phi(t_0,t_i)`, and the
integration produces the forward one.  Inverting a 6x6 matrix at every
accumulation epoch would be correct but would also discard the structure: the
flow of a time-dependent Hamiltonian is symplectic [Hairer2006]_, so the
inverse is available in closed form by transposing blocks
(:func:`symplectic_inverse`) with no factorisation and no conditioning
question.  The same identity, evaluated as a residual, is a free accuracy
diagnostic of the integration (:func:`symplectic_defect`) -- and because
:func:`tda.field.gravity_gradient` symmetrises the gradient, that residual
measures the integrator rather than differencing noise.

References
----------
.. [Tapley2004] B. D. Tapley, B. E. Schutz, G. H. Born, *Statistical Orbit
   Determination*, Elsevier, 2004, Ch. 4 -- variational equations and the
   state-transition matrix.
.. [Montenbruck2000] O. Montenbruck and E. Gill, *Satellite Orbits*, Springer,
   2000, §7.1 -- STM propagation, and the block-transpose inverse of a
   symplectic STM.
.. [Hairer2006] E. Hairer, C. Lubich, G. Wanner, *Geometric Numerical
   Integration*, 2nd ed., Springer, 2006, Ch. VI -- symplecticity of
   Hamiltonian flows and its use as a numerical diagnostic.
.. [Hairer1993] E. Hairer, S. P. Nørsett, G. Wanner, *Solving Ordinary
   Differential Equations I*, 2nd ed., Springer, 1993 -- DOP853.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass

import numpy as np
from numpy.typing import NDArray
from scipy.integrate import solve_ivp

from tda.config import GradientConfig, IntegratorConfig
from tda.field import GravityField, gravity_gradient

__all__ = [
    "SYMPLECTIC_J",
    "IntegrationError",
    "ReferenceArc",
    "estimate_rhs_work_factor",
    "estimate_syntheses_per_rhs",
    "position_rows",
    "propagate",
    "symplectic_defect",
    "symplectic_inverse",
    "velocity_transport",
]

Arr = NDArray[np.float64]

STATE_DIM = 6
STM_DIM = STATE_DIM * STATE_DIM

SYMPLECTIC_J: Arr = np.block([
    [np.zeros((3, 3)), np.eye(3)],
    [-np.eye(3), np.zeros((3, 3))],
])
"""The standard symplectic form :math:`\\mathbf J`, ordering ``(r, v)``."""


class IntegrationError(RuntimeError):
    """Raised when the integrator does not reach the end of the arc.

    Carries the solver's own message.  A failure here is never absorbed into
    a default or a retry with looser tolerances: the campaign's numbers must
    all come from one code path, so a failed arc is reported as failed.
    """


# ---------------------------------------------------------------------------
# Result container
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class ReferenceArc:
    """A reference trajectory, optionally with its state-transition matrices.

    Attributes
    ----------
    t:
        Output epochs, shape ``(M,)``, seconds from arc start.
    r, v:
        Inertial position and velocity, shape ``(M, 3)``.
    stm:
        :math:`\\Phi(t_j, t_0)`, shape ``(M, 6, 6)``, or ``None`` if the arc
        was propagated without the variational equations.
    reference_degree:
        Truncation degree of the field that generated the trajectory.
    gradient_degree:
        Degree at which the gradient was evaluated, or ``None`` if no STM was
        carried.  Recorded separately from ``reference_degree`` because the
        two need not agree and the difference is a declared approximation
        (Q13), not an implementation detail.
    n_rhs:
        Right-hand-side evaluations the solver actually made.  This is the
        realized work the budget accounting needs; a nominal per-call figure
        does not survive contact with an adaptive integrator.

    Notes
    -----
    Frozen, but the arrays it holds are not deep-copied and remain writable.
    Treat the instance as read-only; the freeze prevents rebinding, not
    mutation of the buffers.
    """

    t: Arr
    r: Arr
    v: Arr
    stm: Arr | None
    reference_degree: int
    gradient_degree: int | None
    n_rhs: int

    def __len__(self) -> int:
        """Number of output epochs on the arc."""
        return int(self.t.size)

    @property
    def carries_stm(self) -> bool:
        """Whether the variational equations were integrated alongside."""
        return self.stm is not None

    def radius(self) -> Arr:
        """Selenocentric radius at each epoch, shape ``(M,)``."""
        return np.linalg.norm(self.r, axis=1)

    def speed(self) -> Arr:
        """Inertial speed at each epoch, shape ``(M,)``."""
        return np.linalg.norm(self.v, axis=1)


# ---------------------------------------------------------------------------
# Right-hand side
# ---------------------------------------------------------------------------


def _make_rhs(field: GravityField, degree: int, cfg: GradientConfig | None
              ) -> Callable[[float, Arr], Arr]:
    """Build the (augmented) equations of motion.

    With ``cfg is None`` the state is the plain six-vector and one synthesis
    is spent per call.  Otherwise the state is 42-dimensional and the
    variational block

    .. math::
        \\dot\\Phi = \\begin{pmatrix}\\mathbf 0&\\mathbf I\\\\
                                     \\mathbf G&\\mathbf 0\\end{pmatrix}\\Phi

    is carried alongside [Tapley2004]_.  There is no velocity dependence in
    the dynamics -- the field is a function of position and epoch only -- so
    the upper-right block is exactly the identity and the lower-right block
    is exactly zero; writing them out rather than assembling a 6x6 ``A`` and
    multiplying saves the dominant matrix product.
    """

    def rhs_plain(t: float, y: Arr) -> Arr:
        dy = np.empty(STATE_DIM)
        dy[0:3] = y[3:6]
        dy[3:6] = field.acceleration(y[0:3], t, degree)
        return dy

    if cfg is None:
        return rhs_plain

    def rhs_variational(t: float, y: Arr) -> Arr:
        r = y[0:3]
        dy = np.empty(STATE_DIM + STM_DIM)
        dy[0:3] = y[3:6]
        dy[3:6] = field.acceleration(r, t, degree)

        g = gravity_gradient(field, r, t, degree, cfg)
        phi = y[STATE_DIM:].reshape(STATE_DIM, STATE_DIM)
        dphi = dy[STATE_DIM:].reshape(STATE_DIM, STATE_DIM)
        dphi[0:3, :] = phi[3:6, :]
        dphi[3:6, :] = g @ phi[0:3, :]
        return dy

    return rhs_variational


# ---------------------------------------------------------------------------
# Propagation
# ---------------------------------------------------------------------------


def propagate(field: GravityField,
              state0: Arr,
              t_eval: Arr,
              degree: int,
              integrator: IntegratorConfig,
              gradient: GradientConfig | None = None) -> ReferenceArc:
    """Propagate a reference arc, optionally with its STM.

    Parameters
    ----------
    field:
        Gravity field adapter.  Any object satisfying
        :class:`tda.field.GravityField` will do, which is what lets the tests
        substitute an analytic field with a known gradient.
    state0:
        Initial inertial state ``[r, v]``, shape ``(6,)``, SI.
    t_eval:
        Output epochs in seconds from the arc start, strictly increasing and
        beginning at zero.  This is the *accumulation* grid: the integrator
        chooses its own steps and these are interpolation points.
    degree:
        Reference truncation degree of the trajectory.
    integrator:
        Tolerances and method.  ``atol`` is expanded to a per-component
        vector, tight on velocity; see
        :meth:`tda.config.IntegratorConfig.atol_vector`.
    gradient:
        Gradient settings, or ``None`` to skip the variational equations and
        return an arc with ``stm=None``.  Pilot arcs use ``None``.

    Returns
    -------
    ReferenceArc

    Raises
    ------
    ValueError
        If ``t_eval`` is not a strictly increasing grid starting at zero, or
        ``state0`` is not six-dimensional.
    IntegrationError
        If the solver stops early.

    Notes
    -----
    The initial condition for the variational block is the identity, so
    ``arc.stm[0]`` is :math:`\\mathbf I` up to the output interpolation.

    The augmented system is integrated as *one* system rather than as a
    trajectory followed by a second pass for the STM.  That is deliberate:
    a second pass would have to reconstruct the trajectory by interpolation,
    and the gradient is evaluated at the interpolated point rather than at
    the point the trajectory actually visited -- a small inconsistency that
    the signed method has no reason to tolerate when the alternative costs
    nothing.
    """
    state0 = np.asarray(state0, dtype=float)
    t_eval = np.asarray(t_eval, dtype=float)
    if state0.shape != (STATE_DIM,):
        raise ValueError(f"state0 must have shape (6,), got {state0.shape}")
    if t_eval.ndim != 1 or t_eval.size < 2:
        raise ValueError("t_eval must be a one-dimensional grid of >= 2 epochs")
    if t_eval[0] != 0.0:
        raise ValueError(f"t_eval must start at 0.0, got {t_eval[0]}")
    if not np.all(np.diff(t_eval) > 0.0):
        raise ValueError("t_eval must be strictly increasing")

    with_stm = gradient is not None
    n_extra = STM_DIM if with_stm else 0

    y0 = np.zeros(STATE_DIM + n_extra)
    y0[:STATE_DIM] = state0
    if with_stm:
        y0[STATE_DIM:] = np.eye(STATE_DIM).ravel()

    rhs = _make_rhs(field, degree, gradient)
    sol = solve_ivp(
        rhs,
        (float(t_eval[0]), float(t_eval[-1])),
        y0,
        method=integrator.method,
        t_eval=t_eval,
        rtol=integrator.rtol,
        atol=integrator.atol_vector(n_extra),
        max_step=integrator.max_step_s,
    )
    if not sol.success:
        raise IntegrationError(
            f"integration stopped at t={sol.t[-1] if sol.t.size else 0.0:.3f} s "
            f"of {t_eval[-1]:.3f} s: {sol.message}"
        )

    y = sol.y
    stm = None
    if with_stm:
        stm = np.ascontiguousarray(
            y[STATE_DIM:].T.reshape(-1, STATE_DIM, STATE_DIM)
        )

    return ReferenceArc(
        t=np.ascontiguousarray(sol.t),
        r=np.ascontiguousarray(y[0:3].T),
        v=np.ascontiguousarray(y[3:6].T),
        stm=stm,
        reference_degree=int(degree),
        gradient_degree=None if gradient is None else (
            degree if gradient.degree is None else int(gradient.degree)
        ),
        n_rhs=int(sol.nfev),
    )


# ---------------------------------------------------------------------------
# Symplectic structure
# ---------------------------------------------------------------------------


def symplectic_inverse(phi: Arr) -> Arr:
    """Invert a symplectic state-transition matrix by block transposition.

    For :math:`\\Phi=\\bigl(\\begin{smallmatrix}A&B\\\\C&D\\end{smallmatrix}
    \\bigr)` satisfying :math:`\\Phi^\\top\\mathbf J\\Phi=\\mathbf J`,

    .. math::
        \\Phi^{-1} \\;=\\; -\\mathbf J\\,\\Phi^\\top\\mathbf J
        \\;=\\; \\begin{pmatrix} D^\\top & -B^\\top \\\\
                                -C^\\top & A^\\top \\end{pmatrix},

    a standard identity [Montenbruck2000]_.  Using it instead of a numerical
    inverse removes a factorisation from the inner loop and removes the
    conditioning question entirely: the accuracy of the result is the accuracy
    of :math:`\\Phi` itself, which :func:`symplectic_defect` measures.

    Parameters
    ----------
    phi:
        Shape ``(6, 6)`` or ``(M, 6, 6)``.  Batched input is transposed in
        one pass rather than looped.

    Returns
    -------
    ndarray
        Same shape as ``phi``.

    Warnings
    --------
    The identity is exact only for a symplectic matrix.  It is *not* a
    general inverse and will silently return a wrong answer for one.  Check
    :func:`symplectic_defect` before relying on it; the campaign does so once
    per arc and records the result.
    """
    phi = np.asarray(phi, dtype=float)
    if phi.shape[-2:] != (STATE_DIM, STATE_DIM):
        raise ValueError(f"expected (...,6,6), got {phi.shape}")

    def transposed(block: Arr) -> Arr:
        """Transpose the trailing two axes, leaving any batch axes alone."""
        return np.swapaxes(block, -1, -2)

    out = np.empty_like(phi)
    out[..., 0:3, 0:3] = transposed(phi[..., 3:6, 3:6])   #  D^T
    out[..., 0:3, 3:6] = -transposed(phi[..., 0:3, 3:6])  # -B^T
    out[..., 3:6, 0:3] = -transposed(phi[..., 3:6, 0:3])  # -C^T
    out[..., 3:6, 3:6] = transposed(phi[..., 0:3, 0:3])   #  A^T
    return out


def symplectic_defect(phi: Arr, length_scale: float,
                      time_scale: float) -> Arr:
    """Dimensionless residual of :math:`\\Phi^\\top\\mathbf J\\Phi=\\mathbf J`.

    A free accuracy diagnostic: the exact flow preserves the symplectic form
    [Hairer2006]_, so any residual is integration error.  Because the campaign
    symmetrises the gravity gradient, the residual is not contaminated by
    finite-difference asymmetry and reads as what it is.

    Scaling
    -------
    The raw matrix is dimensionally inhomogeneous -- its position--velocity
    blocks carry seconds and inverse seconds -- so a norm taken on it mixes
    units and is meaningless.  The matrix is first non-dimensionalised by
    :math:`\\mathbf S=\\operatorname{diag}(L,L,L,L/T,L/T,L/T)`,
    :math:`\\tilde\\Phi=\\mathbf S^{-1}\\Phi\\mathbf S`, which leaves the
    symplectic condition invariant because :math:`\\mathbf S` scales
    :math:`\\mathbf J` by a single factor.

    Parameters
    ----------
    phi:
        Shape ``(6, 6)`` or ``(M, 6, 6)``.
    length_scale, time_scale:
        Characteristic scales, e.g. the initial radius and radius over speed.
        Any consistent pair works; the residual is scale-invariant to within
        the conditioning it is measuring.

    Returns
    -------
    ndarray
        Scalar for a single matrix, shape ``(M,)`` for a batch: the maximum
        absolute entry of :math:`\\tilde\\Phi^\\top\\mathbf J\\tilde\\Phi
        -\\mathbf J`.

    Examples
    --------
    The identity is exactly symplectic.

    >>> import numpy as np
    >>> float(symplectic_defect(np.eye(6), 1.0, 1.0))
    0.0
    """
    phi = np.asarray(phi, dtype=float)
    if phi.shape[-2:] != (STATE_DIM, STATE_DIM):
        raise ValueError(f"expected (...,6,6), got {phi.shape}")

    scale = np.concatenate([
        np.full(3, length_scale),
        np.full(3, length_scale / time_scale),
    ])
    # S^-1 Phi S, with S diagonal: divide rows, multiply columns.
    tilde = phi / scale[:, None] * scale[None, :]
    residual = (np.swapaxes(tilde, -1, -2) @ SYMPLECTIC_J @ tilde
                - SYMPLECTIC_J)
    return np.max(np.abs(residual), axis=(-2, -1))


# ---------------------------------------------------------------------------
# Transport helpers
# ---------------------------------------------------------------------------


def velocity_transport(phi_inverse: Arr) -> Arr:
    """Extract :math:`\\Phi(t_0,t_i)\\mathbf B`, the columns acceleration hits.

    :math:`\\mathbf B` maps an acceleration into the velocity block of the
    state, so :math:`\\Phi\\mathbf B` is simply the last three columns of
    :math:`\\Phi`.  Forming :math:`\\mathbf B` and multiplying would allocate
    a 6x3 matrix and do a 6x6 by 6x3 product per epoch to reproduce a slice;
    this returns the slice.

    Parameters
    ----------
    phi_inverse:
        :math:`\\Phi(t_0,t_i)`, shape ``(...,6,6)`` -- typically the output of
        :func:`symplectic_inverse`.

    Returns
    -------
    ndarray, shape ``(...,6,3)``
        Multiply by :math:`\\Delta\\mathbf a\\,\\Delta t` to obtain
        :math:`\\mathbf u_i`.
    """
    return np.asarray(phi_inverse, dtype=float)[..., :, 3:6]


def position_rows(phi: Arr) -> Arr:
    """Extract :math:`\\mathbf H_r\\Phi`, the position rows.

    The objective selects position before taking a norm, and
    :math:`\\mathbf H_r=[\\,\\mathbf I_3\\;\\;\\mathbf 0\\,]` is a row slice.
    The per-epoch block of the objective is then
    :math:`\\mathbf M_j=(\\mathbf H_r\\Phi_j)^\\top(\\mathbf H_r\\Phi_j)`,
    which :mod:`tda.kernel` forms from this.

    Parameters
    ----------
    phi:
        Shape ``(...,6,6)``.

    Returns
    -------
    ndarray, shape ``(...,3,6)``
    """
    return np.asarray(phi, dtype=float)[..., 0:3, :]


def estimate_syntheses_per_rhs(gradient: GradientConfig | None) -> int:
    """Number of full syntheses one right-hand-side evaluation performs.

    One for the acceleration, plus six for a central-difference gradient when
    the variational equations are carried.  This is a *count*; it is the right
    number for predicting call volume and the wrong one for predicting cost,
    because a synthesis at a lower degree is cheaper.  Use
    :func:`estimate_rhs_work_factor` for cost.

    Examples
    --------
    >>> estimate_syntheses_per_rhs(None)
    1
    >>> from tda.config import GradientConfig
    >>> estimate_syntheses_per_rhs(GradientConfig())
    7
    """
    return 1 if gradient is None else 7


def estimate_rhs_work_factor(gradient: GradientConfig | None,
                             reference_degree: int) -> float:
    """Quadratic-work multiplier of a variational right-hand side.

    Synthesis cost scales as :math:`N^2`, which is what the campaign's budget
    counts, so six gradient evaluations at degree :math:`n_g` cost
    :math:`6(n_g/N)^2` times the trajectory's own synthesis rather than six
    times it:

    .. math::
        w \\;=\\; 1 + 6\\,(n_g/N)^2 .

    Reported into the manifest so that the cost of stage M1 is computed rather
    than asserted, and so that the price of the open gradient-degree question
    (``DECISIONS.md`` Q13) is a number: dropping the gradient from the
    reference degree to half of it takes the factor from 7 to 2.5.

    Parameters
    ----------
    gradient:
        Gradient settings, or ``None`` for a plain propagation.
    reference_degree:
        Truncation degree of the trajectory, the denominator of the ratio.

    Raises
    ------
    ValueError
        If ``reference_degree`` is not positive.

    Examples
    --------
    >>> from tda.config import GradientConfig
    >>> estimate_rhs_work_factor(None, 300)
    1.0
    >>> estimate_rhs_work_factor(GradientConfig(), 300)
    7.0
    >>> estimate_rhs_work_factor(GradientConfig(degree=150), 300)
    2.5
    """
    if reference_degree <= 0:
        raise ValueError(
            f"reference_degree must be positive, got {reference_degree}")
    if gradient is None:
        return 1.0
    n_g = reference_degree if gradient.degree is None else gradient.degree
    return 1.0 + 6.0 * (n_g / reference_degree) ** 2
