"""Reference trajectory and its state-transition matrix.

This module answers the plan's open question Q12: **where does** :math:`\\Phi`
**come from?**  The whole allocation rests on it -- the coupling matrix
:math:`\\mathbf Q` is generated by nothing else -- and the archive does not
supply it.  The previous campaign integrated the *forced* variational system
:math:`\\delta\\ddot{\\mathbf r}=\\mathbf G\\,\\delta\\mathbf r+\\Delta\\mathbf a`
once per policy and stored the resulting deviation, never the 6x6 matrix.  A
deviation cannot be reused for a different forcing, so the matrix has to be
integrated here.

Cost, stated plainly
--------------------
Carrying :math:`\\Phi` means 36 extra states and one gravity gradient per
right-hand side.  With a central-difference gradient that is six syntheses on
top of the one the trajectory needs, so a variational arc costs roughly seven
times a plain propagation at equal gradient degree -- less if the gradient is
truncated below the reference degree, which is exactly the trade the plan
flags as open (Q13).  Stage M1 is therefore *not* free of integration, and
:func:`estimate_syntheses_per_rhs` exists so that the number entering the
manifest is computed rather than asserted.

What this module does not contain
---------------------------------
The algebra of :math:`\\Phi` -- the symplectic inverse that supplies the
backward transport, the residual that diagnoses the integration, the row and
column slices the objective needs -- is :mod:`tda.stm`.  It is separate
because it depends on neither a gravity model nor an integrator, so a failure
there is unambiguous; a test that exercised the inverse *through* a
propagation could not say which of the two was wrong.

References
----------
.. [Tapley2004] B. D. Tapley, B. E. Schutz, G. H. Born, *Statistical Orbit
   Determination*, Elsevier, 2004, Ch. 4 -- variational equations and the
   state-transition matrix.
.. [Montenbruck2000] O. Montenbruck and E. Gill, *Satellite Orbits*, Springer,
   2000, §7.1 -- state-transition matrix propagation.
.. [Hairer1993] E. Hairer, S. P. Nørsett, G. Wanner, *Solving Ordinary
   Differential Equations I*, 2nd ed., Springer, 1993 -- DOP853.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass

import numpy as np
from numpy.typing import NDArray
from scipy.integrate import solve_ivp

from tda.config import GradientConfig, IntegratorConfig
from tda.field import GravityField, gravity_gradient
from tda.stm import STATE_DIM

__all__ = [
    "IntegrationError",
    "ReferenceArc",
    "estimate_rhs_work_factor",
    "estimate_syntheses_per_rhs",
    "propagate",
]

Arr = NDArray[np.float64]

STM_DIM = STATE_DIM * STATE_DIM


class IntegrationError(RuntimeError):
    """Raised when the integrator does not reach the end of the arc.

    Carries the solver's own message.  A failure here is never absorbed into
    a default or a retry with looser tolerances: the campaign's numbers must
    all come from one code path, so a failed arc is reported as failed.
    """


# ---------------------------------------------------------------------------
# Result container
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class ReferenceArc:
    """A reference trajectory, optionally with its state-transition matrices.

    Attributes
    ----------
    t:
        Output epochs, shape ``(M,)``, seconds from arc start.
    r, v:
        Inertial position and velocity, shape ``(M, 3)``.
    stm:
        :math:`\\Phi(t_j, t_0)`, shape ``(M, 6, 6)``, or ``None`` if the arc
        was propagated without the variational equations.
    reference_degree:
        Truncation degree of the field that generated the trajectory.
    gradient_degree:
        Degree at which the gradient was evaluated, or ``None`` if no STM was
        carried.  Recorded separately from ``reference_degree`` because the
        two need not agree and the difference is a declared approximation
        (Q13), not an implementation detail.
    n_rhs:
        Right-hand-side evaluations the solver actually made.  This is the
        realized work the budget accounting needs; a nominal per-call figure
        does not survive contact with an adaptive integrator.

    Notes
    -----
    Frozen, but the arrays it holds are not deep-copied and remain writable.
    Treat the instance as read-only; the freeze prevents rebinding, not
    mutation of the buffers.
    """

    t: Arr
    r: Arr
    v: Arr
    stm: Arr | None
    reference_degree: int
    gradient_degree: int | None
    n_rhs: int

    def __len__(self) -> int:
        """Number of output epochs on the arc."""
        return int(self.t.size)

    @property
    def carries_stm(self) -> bool:
        """Whether the variational equations were integrated alongside."""
        return self.stm is not None

    def radius(self) -> Arr:
        """Selenocentric radius at each epoch, shape ``(M,)``."""
        return np.linalg.norm(self.r, axis=1)

    def speed(self) -> Arr:
        """Inertial speed at each epoch, shape ``(M,)``."""
        return np.linalg.norm(self.v, axis=1)


# ---------------------------------------------------------------------------
# Right-hand side
# ---------------------------------------------------------------------------


def _make_rhs(field: GravityField, degree: int, cfg: GradientConfig | None
              ) -> Callable[[float, Arr], Arr]:
    """Build the (augmented) equations of motion.

    With ``cfg is None`` the state is the plain six-vector and one synthesis
    is spent per call.  Otherwise the state is 42-dimensional and the
    variational block

    .. math::
        \\dot\\Phi = \\begin{pmatrix}\\mathbf 0&\\mathbf I\\\\
                                     \\mathbf G&\\mathbf 0\\end{pmatrix}\\Phi

    is carried alongside [Tapley2004]_.  There is no velocity dependence in
    the dynamics -- the field is a function of position and epoch only -- so
    the upper-right block is exactly the identity and the lower-right block
    is exactly zero; writing them out rather than assembling a 6x6 ``A`` and
    multiplying saves the dominant matrix product.
    """

    def rhs_plain(t: float, y: Arr) -> Arr:
        dy = np.empty(STATE_DIM)
        dy[0:3] = y[3:6]
        dy[3:6] = field.acceleration(y[0:3], t, degree)
        return dy

    if cfg is None:
        return rhs_plain

    def rhs_variational(t: float, y: Arr) -> Arr:
        r = y[0:3]
        dy = np.empty(STATE_DIM + STM_DIM)
        dy[0:3] = y[3:6]
        dy[3:6] = field.acceleration(r, t, degree)

        g = gravity_gradient(field, r, t, degree, cfg)
        phi = y[STATE_DIM:].reshape(STATE_DIM, STATE_DIM)
        dphi = dy[STATE_DIM:].reshape(STATE_DIM, STATE_DIM)
        dphi[0:3, :] = phi[3:6, :]
        dphi[3:6, :] = g @ phi[0:3, :]
        return dy

    return rhs_variational


# ---------------------------------------------------------------------------
# Propagation
# ---------------------------------------------------------------------------


def propagate(field: GravityField,
              state0: Arr,
              t_eval: Arr,
              degree: int,
              integrator: IntegratorConfig,
              gradient: GradientConfig | None = None) -> ReferenceArc:
    """Propagate a reference arc, optionally with its STM.

    Parameters
    ----------
    field:
        Gravity field adapter.  Any object satisfying
        :class:`tda.field.GravityField` will do, which is what lets the tests
        substitute an analytic field with a known gradient.
    state0:
        Initial inertial state ``[r, v]``, shape ``(6,)``, SI.
    t_eval:
        Output epochs in seconds from the arc start, strictly increasing and
        beginning at zero.  This is the *accumulation* grid: the integrator
        chooses its own steps and these are interpolation points.
    degree:
        Reference truncation degree of the trajectory.
    integrator:
        Tolerances and method.  ``atol`` is expanded to a per-component
        vector, tight on velocity; see
        :meth:`tda.config.IntegratorConfig.atol_vector`.
    gradient:
        Gradient settings, or ``None`` to skip the variational equations and
        return an arc with ``stm=None``.  Pilot arcs use ``None``.

    Returns
    -------
    ReferenceArc

    Raises
    ------
    ValueError
        If ``t_eval`` is not a strictly increasing grid starting at zero, or
        ``state0`` is not six-dimensional.
    IntegrationError
        If the solver stops early.

    Notes
    -----
    The initial condition for the variational block is the identity, so
    ``arc.stm[0]`` is :math:`\\mathbf I` up to the output interpolation.

    The augmented system is integrated as *one* system rather than as a
    trajectory followed by a second pass for the STM.  That is deliberate:
    a second pass would have to reconstruct the trajectory by interpolation,
    and the gradient is evaluated at the interpolated point rather than at
    the point the trajectory actually visited -- a small inconsistency that
    the signed method has no reason to tolerate when the alternative costs
    nothing.
    """
    state0 = np.asarray(state0, dtype=float)
    t_eval = np.asarray(t_eval, dtype=float)
    if state0.shape != (STATE_DIM,):
        raise ValueError(f"state0 must have shape (6,), got {state0.shape}")
    if t_eval.ndim != 1 or t_eval.size < 2:
        raise ValueError("t_eval must be a one-dimensional grid of >= 2 epochs")
    if t_eval[0] != 0.0:
        raise ValueError(f"t_eval must start at 0.0, got {t_eval[0]}")
    if not np.all(np.diff(t_eval) > 0.0):
        raise ValueError("t_eval must be strictly increasing")

    with_stm = gradient is not None
    n_extra = STM_DIM if with_stm else 0

    y0 = np.zeros(STATE_DIM + n_extra)
    y0[:STATE_DIM] = state0
    if with_stm:
        y0[STATE_DIM:] = np.eye(STATE_DIM).ravel()

    rhs = _make_rhs(field, degree, gradient)
    sol = solve_ivp(
        rhs,
        (float(t_eval[0]), float(t_eval[-1])),
        y0,
        method=integrator.method,
        t_eval=t_eval,
        rtol=integrator.rtol,
        atol=integrator.atol_vector(n_extra),
        max_step=integrator.max_step_s,
    )
    if not sol.success:
        raise IntegrationError(
            f"integration stopped at t={sol.t[-1] if sol.t.size else 0.0:.3f} s "
            f"of {t_eval[-1]:.3f} s: {sol.message}"
        )

    y = sol.y
    stm = None
    if with_stm:
        stm = np.ascontiguousarray(
            y[STATE_DIM:].T.reshape(-1, STATE_DIM, STATE_DIM)
        )

    return ReferenceArc(
        t=np.ascontiguousarray(sol.t),
        r=np.ascontiguousarray(y[0:3].T),
        v=np.ascontiguousarray(y[3:6].T),
        stm=stm,
        reference_degree=int(degree),
        gradient_degree=None if gradient is None else (
            degree if gradient.degree is None else int(gradient.degree)
        ),
        n_rhs=int(sol.nfev),
    )


def estimate_syntheses_per_rhs(gradient: GradientConfig | None) -> int:
    """Number of full syntheses one right-hand-side evaluation performs.

    One for the acceleration, plus six for a central-difference gradient when
    the variational equations are carried.  This is a *count*; it is the right
    number for predicting call volume and the wrong one for predicting cost,
    because a synthesis at a lower degree is cheaper.  Use
    :func:`estimate_rhs_work_factor` for cost.

    Examples
    --------
    >>> estimate_syntheses_per_rhs(None)
    1
    >>> from tda.config import GradientConfig
    >>> estimate_syntheses_per_rhs(GradientConfig())
    7
    """
    return 1 if gradient is None else 7


def estimate_rhs_work_factor(gradient: GradientConfig | None,
                             reference_degree: int) -> float:
    """Quadratic-work multiplier of a variational right-hand side.

    Synthesis cost scales as :math:`N^2`, which is what the campaign's budget
    counts, so six gradient evaluations at degree :math:`n_g` cost
    :math:`6(n_g/N)^2` times the trajectory's own synthesis rather than six
    times it:

    .. math::
        w \\;=\\; 1 + 6\\,(n_g/N)^2 .

    Reported into the manifest so that the cost of stage M1 is computed rather
    than asserted, and so that the price of the open gradient-degree question
    (``DECISIONS.md`` Q13) is a number: dropping the gradient from the
    reference degree to half of it takes the factor from 7 to 2.5.

    Parameters
    ----------
    gradient:
        Gradient settings, or ``None`` for a plain propagation.
    reference_degree:
        Truncation degree of the trajectory, the denominator of the ratio.

    Raises
    ------
    ValueError
        If ``reference_degree`` is not positive.

    Examples
    --------
    >>> from tda.config import GradientConfig
    >>> estimate_rhs_work_factor(None, 300)
    1.0
    >>> estimate_rhs_work_factor(GradientConfig(), 300)
    7.0
    >>> estimate_rhs_work_factor(GradientConfig(degree=150), 300)
    2.5
    """
    if reference_degree <= 0:
        raise ValueError(
            f"reference_degree must be positive, got {reference_degree}")
    if gradient is None:
        return 1.0
    n_g = reference_degree if gradient.degree is None else gradient.degree
    return 1.0 + 6.0 * (n_g / reference_degree) ** 2
