"""Verification of the reference propagation and the state-transition matrix.

The load-bearing test is :func:`test_stm_matches_finite_difference_of_flow`.
Every later result in the campaign is generated by :math:`\\Phi`, and the only
way to know the variational block is right is to compare it against what it
claims to be -- the derivative of the flow with respect to the initial state.
Symplecticity is necessary but not sufficient: a variational block with a
transposed gradient would still be symplectic and still be wrong.

All fixtures use the analytic fields of :mod:`tda.analytic`, so the suite runs
without the spherical-harmonic kernel installed.
"""

from __future__ import annotations

import numpy as np
import pytest

from conftest import J2_MOON, MU_MOON, R_MOON
from tda.analytic import J2Field, PointMassField
from tda.config import GradientConfig
from tda.dynamics import (
    IntegrationError,
    estimate_rhs_work_factor,
    estimate_syntheses_per_rhs,
    propagate,
    propagate_schedule,
)
from tda.stm import symplectic_defect

# ---------------------------------------------------------------------------
# The analytic gradient
# ---------------------------------------------------------------------------


def test_point_mass_gradient_is_symmetric_and_traceless() -> None:
    """Laplace's equation in free space: the Hessian of ``1/r`` is traceless."""
    field = PointMassField(mu=MU_MOON)
    r = np.array([1.8e6, 3.0e5, -7.0e5])
    g = field.exact_gradient(r)
    assert np.array_equal(g, g.T), "an outer product is exactly symmetric"
    assert abs(np.trace(g)) < 1e-12 * abs(g[0, 0])


def test_finite_difference_gradient_matches_the_closed_form() -> None:
    """Prices the central-difference estimator against a known answer.

    This is the check that licenses using a differenced gradient on the real
    field, where no closed form is available.
    """
    from tda.field import gravity_gradient

    field = PointMassField(mu=MU_MOON)
    r = np.array([1.8e6, 3.0e5, -7.0e5])
    numeric = gravity_gradient(field, r, 0.0, 0, GradientConfig(step_m=1.0))
    exact = field.exact_gradient(r)
    # A central difference truncates at O(h^2 a'''), which at these radii is
    # ~1e-7 relative; the tolerance states that rather than pinning digits the
    # estimator does not have.
    assert np.allclose(numeric, exact, rtol=1e-6,
                       atol=1e-9 * float(np.max(np.abs(exact))))


# ---------------------------------------------------------------------------
# Propagation
# ---------------------------------------------------------------------------


def test_circular_orbit_closes(circular_state, tight) -> None:
    """A point-mass circular orbit returns to its initial state in one period."""
    field = PointMassField(mu=MU_MOON)
    r0 = float(np.linalg.norm(circular_state[:3]))
    period = 2.0 * np.pi * np.sqrt(r0**3 / MU_MOON)
    t_eval = np.array([0.0, period])

    arc = propagate(field, circular_state, t_eval, 0, tight)

    assert not arc.carries_stm
    # rtol=0 on purpose: the default 1e-5 would be relative to a 1.8e6 m
    # radius, i.e. an 18 m tolerance, and the test would pass on a broken
    # propagator.
    assert np.allclose(arc.r[-1], circular_state[:3], rtol=0.0, atol=1e-3)
    assert np.allclose(arc.v[-1], circular_state[3:], rtol=0.0, atol=1e-6)


def test_stm_starts_at_identity(circular_state, tight) -> None:
    field = PointMassField(mu=MU_MOON)
    arc = propagate(field, circular_state, np.array([0.0, 60.0, 120.0]), 0,
                    tight, GradientConfig())
    assert arc.carries_stm
    assert np.allclose(arc.stm[0], np.eye(6), rtol=0.0, atol=1e-12)


def test_stm_matches_finite_difference_of_flow(circular_state, tight) -> None:
    """:math:`\\Phi` is the Jacobian of the flow. Verify it as one.

    Six perturbed propagations, differenced against six more, give the
    columns of :math:`\\partial\\mathbf x(t)/\\partial\\mathbf x(t_0)`
    directly.  A transposed or mis-blocked variational term fails here and
    passes every structural check, which is why this test exists.

    The :math:`J_2` field is used rather than a point mass so that the
    position--position block is not degenerate.
    """
    field = J2Field(mu=MU_MOON, reference_radius=R_MOON, j2=J2_MOON)
    span = 1800.0
    t_eval = np.array([0.0, span])
    # Symmetric perturbations: metres in position, mm/s in velocity, both
    # far above roundoff and far below the scale on which the flow curves.
    steps = np.array([1.0, 1.0, 1.0, 1.0e-3, 1.0e-3, 1.0e-3])

    arc = propagate(field, circular_state, t_eval, 2, tight, GradientConfig())
    phi_integrated = arc.stm[-1]

    phi_numeric = np.empty((6, 6))
    for j in range(6):
        bump = np.zeros(6)
        bump[j] = steps[j]
        plus = propagate(field, circular_state + bump, t_eval, 2, tight)
        minus = propagate(field, circular_state - bump, t_eval, 2, tight)
        end_plus = np.concatenate([plus.r[-1], plus.v[-1]])
        end_minus = np.concatenate([minus.r[-1], minus.v[-1]])
        phi_numeric[:, j] = (end_plus - end_minus) / (2.0 * steps[j])

    # Compare column by column: the columns have wildly different magnitudes
    # (a velocity column carries seconds), so a single absolute tolerance
    # would be vacuous for some and impossible for others.
    for j in range(6):
        scale = np.max(np.abs(phi_numeric[:, j]))
        assert np.allclose(phi_integrated[:, j], phi_numeric[:, j],
                           rtol=1e-6, atol=1e-8 * scale), f"column {j}"


def test_stm_stays_symplectic_over_an_orbit(circular_state, tight) -> None:
    """The integration diagnostic the campaign records once per arc."""
    field = J2Field(mu=MU_MOON, reference_radius=R_MOON, j2=J2_MOON)
    r0 = float(np.linalg.norm(circular_state[:3]))
    period = 2.0 * np.pi * np.sqrt(r0**3 / MU_MOON)
    t_eval = np.linspace(0.0, period, 25)

    arc = propagate(field, circular_state, t_eval, 2, tight, GradientConfig())
    speed0 = float(np.linalg.norm(circular_state[3:]))
    defect = symplectic_defect(arc.stm, r0, r0 / speed0)

    assert defect.shape == (25,)
    assert float(np.max(defect)) < 1.0e-9


def test_gradient_degree_is_recorded(circular_state, tight) -> None:
    """The resolved gradient degree must be recorded, not left as ``None``.

    Q13 -- which gradient degree the benchmark STM is built at -- turns on
    this number being auditable after the fact.
    """
    field = J2Field(mu=MU_MOON, reference_radius=R_MOON, j2=J2_MOON)
    t_eval = np.array([0.0, 60.0])

    matched = propagate(field, circular_state, t_eval, 2, tight,
                        GradientConfig(degree=None))
    explicit = propagate(field, circular_state, t_eval, 2, tight,
                         GradientConfig(degree=1))

    assert matched.gradient_degree == 2
    assert explicit.gradient_degree == 1
    assert propagate(field, circular_state, t_eval, 2,
                     tight).gradient_degree is None


def test_realized_rhs_count_is_reported(circular_state, tight) -> None:
    """Budget accounting needs realized work, not a nominal per-call figure."""
    field = PointMassField(mu=MU_MOON)
    arc = propagate(field, circular_state, np.linspace(0.0, 600.0, 6), 0, tight)
    assert arc.n_rhs > 0


# ---------------------------------------------------------------------------
# Input validation
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(("t_eval", "message"), [
    (np.array([60.0, 120.0]), "start at 0.0"),
    (np.array([0.0, 120.0, 60.0]), "strictly increasing"),
    (np.array([0.0]), "at least|>= 2|2 epochs"),
])
def test_bad_grid_is_rejected(circular_state, tight, t_eval, message) -> None:
    field = PointMassField(mu=MU_MOON)
    with pytest.raises(ValueError, match=message):
        propagate(field, circular_state, t_eval, 0, tight)


def test_bad_state_is_rejected(tight) -> None:
    field = PointMassField(mu=MU_MOON)
    with pytest.raises(ValueError, match=r"shape \(6,\)"):
        propagate(field, np.zeros(3), np.array([0.0, 60.0]), 0, tight)


def test_integration_failure_is_raised_not_absorbed(tight) -> None:
    """A collision course drives the solver into the singularity.

    Free-fall from rest at ``R_MOON`` reaches the origin in
    :math:`(\\pi/2)\\sqrt{r^3/2\\mu}\\approx 1150` s, so a span of 2000 s is
    past it with margin and the test does not depend on how long the solver
    thrashes.  The point is that the failure surfaces rather than being
    absorbed into a shorter arc or a looser retry.
    """
    field = PointMassField(mu=MU_MOON)
    radial_infall = np.array([R_MOON, 0.0, 0.0, 0.0, 0.0, 0.0])
    with pytest.raises(IntegrationError):
        propagate(field, radial_infall, np.array([0.0, 2.0e3]), 0, tight)


def test_synthesis_count_is_explicit() -> None:
    assert estimate_syntheses_per_rhs(None) == 1
    assert estimate_syntheses_per_rhs(GradientConfig()) == 7


def test_work_factor_prices_the_gradient_degree() -> None:
    """Cost scales as N^2, so a cheaper gradient is cheaper than 6x.

    This is the number that prices the open question Q13: matching the
    reference degree costs 7x a plain propagation, halving it costs 2.5x.
    """
    assert estimate_rhs_work_factor(None, 300) == 1.0
    assert estimate_rhs_work_factor(GradientConfig(), 300) == pytest.approx(7.0)
    assert estimate_rhs_work_factor(GradientConfig(degree=150), 300) == \
        pytest.approx(2.5)
    assert estimate_rhs_work_factor(GradientConfig(degree=120), 600) == \
        pytest.approx(1.24)
    with pytest.raises(ValueError, match="positive"):
        estimate_rhs_work_factor(GradientConfig(), 0)


# ---------------------------------------------------------------------------
# Flying a schedule
# ---------------------------------------------------------------------------


def test_a_constant_schedule_reproduces_the_fixed_degree_arc(
        circular_state, orbital_period, tight) -> None:
    """The two code paths must agree where they overlap.

    A one-interval schedule is a fixed degree, so any difference between
    propagate_schedule and propagate is a bug in the schedule machinery and
    not a property of switching.
    """
    field = J2Field(MU_MOON, R_MOON, J2_MOON)
    times = np.linspace(0.0, orbital_period, 60)
    edges = np.array([0.0, orbital_period])

    plain = propagate(field, circular_state, times, 2, tight, None)
    flown, work = propagate_schedule(field, circular_state, times, edges,
                                     np.array([2]), tight)

    assert flown.r == pytest.approx(plain.r, rel=1e-11, abs=1e-6)
    assert work.calls == plain.n_rhs
    assert work.quadratic == pytest.approx(4.0 * plain.n_rhs)
    assert work.per_degree == {2: plain.n_rhs}


def test_the_realized_work_is_counted_at_the_call_not_predicted(
        circular_state, orbital_period, tight) -> None:
    """Two degrees, and the split is measured rather than assumed uniform."""
    field = J2Field(MU_MOON, R_MOON, J2_MOON)
    times = np.linspace(0.0, orbital_period, 80)
    edges = np.array([0.0, 0.5 * orbital_period, orbital_period])

    _, work = propagate_schedule(field, circular_state, times, edges,
                                 np.array([2, 4]), tight)

    assert set(work.per_degree) == {2, 4}
    assert sum(work.per_degree.values()) == work.calls
    assert work.quadratic == pytest.approx(
        4.0 * work.per_degree[2] + 16.0 * work.per_degree[4])
    # Nominal work would split the calls evenly between the halves; the
    # measured split need not, and that difference is the point.
    assert work.mean_squared_degree == pytest.approx(
        work.quadratic / work.calls)


def test_a_schedule_that_does_not_match_its_edges_is_refused(
        circular_state, orbital_period, tight) -> None:
    field = J2Field(MU_MOON, R_MOON, J2_MOON)
    times = np.linspace(0.0, orbital_period, 20)
    with pytest.raises(ValueError, match="decision_edges must have"):
        propagate_schedule(field, circular_state, times,
                           np.array([0.0, orbital_period]),
                           np.array([2, 4]), tight)
    with pytest.raises(ValueError, match="must be positive"):
        propagate_schedule(field, circular_state, times,
                           np.array([0.0, orbital_period]),
                           np.array([0]), tight)
