"""Verification of the reference propagation and the state-transition matrix.

The load-bearing test is :func:`test_stm_matches_finite_difference_of_flow`.
Every later result in the campaign is generated by :math:`\\Phi`, and the only
way to know the variational block is right is to compare it against what it
claims to be -- the derivative of the flow with respect to the initial state.
Symplecticity is necessary but not sufficient: a variational block with a
transposed gradient would still be symplectic and still be wrong.

All fixtures use the analytic fields of :mod:`tda.analytic`, so the suite runs
without the spherical-harmonic kernel installed.
"""

from __future__ import annotations

import numpy as np
import pytest

from tda.analytic import J2Field, PointMassField
from tda.config import GradientConfig, IntegratorConfig
from tda.dynamics import (
    SYMPLECTIC_J,
    IntegrationError,
    estimate_rhs_work_factor,
    estimate_syntheses_per_rhs,
    position_rows,
    propagate,
    symplectic_defect,
    symplectic_inverse,
    velocity_transport,
)

MU_MOON = 4.902800118e12
R_MOON = 1.7374e6
J2_MOON = 2.033e-4


@pytest.fixture(scope="module")
def circular_state() -> np.ndarray:
    """A 100 km circular orbit, inclined so that :math:`J_2` acts."""
    r = R_MOON + 1.0e5
    speed = np.sqrt(MU_MOON / r)
    inc = np.deg2rad(45.0)
    return np.array([r, 0.0, 0.0,
                     0.0, speed * np.cos(inc), speed * np.sin(inc)])


@pytest.fixture(scope="module")
def tight() -> IntegratorConfig:
    return IntegratorConfig(rtol=1.0e-12, atol_position_m=1.0e-9,
                            atol_velocity_m_s=1.0e-12, max_step_s=60.0)


# ---------------------------------------------------------------------------
# Symplectic algebra
# ---------------------------------------------------------------------------


def _random_symplectic(rng: np.random.Generator) -> np.ndarray:
    """Build a symplectic matrix as the exponential of a Hamiltonian one.

    ``H = J S`` with ``S`` symmetric is Hamiltonian, and ``expm(H)`` is
    symplectic.  A small scaling keeps the exponential well conditioned so
    the test measures the identity rather than the matrix exponential.
    """
    from scipy.linalg import expm

    s = rng.normal(size=(6, 6))
    s = 0.5 * (s + s.T)
    return expm(0.05 * SYMPLECTIC_J @ s)


def test_symplectic_inverse_is_an_inverse() -> None:
    rng = np.random.default_rng(20260808)
    for _ in range(8):
        phi = _random_symplectic(rng)
        assert np.allclose(symplectic_inverse(phi) @ phi, np.eye(6),
                           rtol=0.0, atol=1e-12)


def test_symplectic_inverse_is_batched() -> None:
    rng = np.random.default_rng(1)
    batch = np.stack([_random_symplectic(rng) for _ in range(5)])
    inv = symplectic_inverse(batch)
    assert inv.shape == batch.shape
    assert np.allclose(inv @ batch, np.eye(6)[None], rtol=0.0, atol=1e-12)


def test_symplectic_defect_vanishes_on_identity() -> None:
    assert symplectic_defect(np.eye(6), 1.0, 1.0) == 0.0


def test_free_drift_shear_is_symplectic() -> None:
    """Not every off-diagonal term breaks the form, and it matters which.

    ``I + tau*e_0 e_3^T`` is one component of free drift, and free drift is a
    Hamiltonian flow, so the residual vanishes identically -- at first order
    *and* at second, since ``E^T J E = 0`` for ``E = e_0 e_3^T``.  Recorded as
    a test because it is the trap a hand-written "obviously wrong" matrix
    falls into: perturbing a position row towards its *own* velocity column
    produces a matrix that is still symplectic.
    """
    shear = np.eye(6)
    shear[0, 3] = 1.0e-3
    assert symplectic_defect(shear, 1.0, 1.0) == pytest.approx(0.0, abs=1e-15)


@pytest.mark.parametrize(("index", "value", "why"), [
    ((0, 0), 1.1, "position scaled with no compensating velocity contraction"),
    ((0, 4), 1.0e-3, "x coupled to v_y; J e_0 = -e_3, so e_0 e_4^T is not "
                     "Hamiltonian"),
    ((1, 3), 1.0e-3, "y coupled to v_x; J e_1 = -e_4, so e_1 e_3^T is not "
                     "Hamiltonian"),
])
def test_symplectic_defect_detects_a_broken_matrix(index, value, why) -> None:
    """A matrix that is not symplectic must not pass silently.

    Guards the warning in :func:`symplectic_inverse`: the block-transpose
    identity returns a wrong answer for a general matrix, so the defect is the
    only thing standing between a bad integration and a plausible number.

    The perturbations are chosen against the criterion rather than by eye.
    For :math:`\\Phi=\\mathbf I+\\varepsilon\\,\\mathbf e_a\\mathbf e_b^\\top`
    the first-order residual vanishes exactly when
    :math:`\\mathbf J\\mathbf e_a\\propto\\mathbf e_b`, and the second-order
    term :math:`\\mathbf E^\\top\\mathbf J\\mathbf E` vanishes for every
    rank-one :math:`\\mathbf E`.  Picking a pair that satisfies the
    proportionality would therefore give a *symplectic* matrix and a test that
    silently proves nothing -- which is what
    :func:`test_free_drift_shear_is_symplectic` records.
    """
    broken = np.eye(6)
    broken[index] = value
    assert symplectic_defect(broken, 1.0, 1.0) > 1.0e-6, why


def test_symplectic_defect_is_scale_invariant() -> None:
    """The dimensionless residual must not depend on the chosen units."""
    rng = np.random.default_rng(7)
    phi = _random_symplectic(rng)
    # Re-express the same operator in units where length and time differ.
    scale = np.concatenate([np.full(3, 1.0e6), np.full(3, 1.0e6 / 5.0e3)])
    dimensional = phi * scale[:, None] / scale[None, :]
    a = symplectic_defect(phi, 1.0, 1.0)
    b = symplectic_defect(dimensional, 1.0e6, 5.0e3)
    # Both are roundoff-level; what is asserted is that re-expressing the same
    # operator in other units does not manufacture a defect. Without the
    # non-dimensionalisation, ``b`` would be of order the scale factors.
    assert b == pytest.approx(a, rel=1e-6, abs=1e-12)
    assert b < 1.0e-12


# ---------------------------------------------------------------------------
# The analytic gradient
# ---------------------------------------------------------------------------


def test_point_mass_gradient_is_symmetric_and_traceless() -> None:
    """Laplace's equation in free space: the Hessian of ``1/r`` is traceless."""
    field = PointMassField(mu=MU_MOON)
    r = np.array([1.8e6, 3.0e5, -7.0e5])
    g = field.exact_gradient(r)
    assert np.array_equal(g, g.T), "an outer product is exactly symmetric"
    assert abs(np.trace(g)) < 1e-12 * abs(g[0, 0])


def test_finite_difference_gradient_matches_the_closed_form() -> None:
    """Prices the central-difference estimator against a known answer.

    This is the check that licenses using a differenced gradient on the real
    field, where no closed form is available.
    """
    from tda.field import gravity_gradient

    field = PointMassField(mu=MU_MOON)
    r = np.array([1.8e6, 3.0e5, -7.0e5])
    numeric = gravity_gradient(field, r, 0.0, 0, GradientConfig(step_m=1.0))
    exact = field.exact_gradient(r)
    # A central difference truncates at O(h^2 a'''), which at these radii is
    # ~1e-7 relative; the tolerance states that rather than pinning digits the
    # estimator does not have.
    assert np.allclose(numeric, exact, rtol=1e-6,
                       atol=1e-9 * float(np.max(np.abs(exact))))


# ---------------------------------------------------------------------------
# Propagation
# ---------------------------------------------------------------------------


def test_circular_orbit_closes(circular_state, tight) -> None:
    """A point-mass circular orbit returns to its initial state in one period."""
    field = PointMassField(mu=MU_MOON)
    r0 = float(np.linalg.norm(circular_state[:3]))
    period = 2.0 * np.pi * np.sqrt(r0**3 / MU_MOON)
    t_eval = np.array([0.0, period])

    arc = propagate(field, circular_state, t_eval, 0, tight)

    assert not arc.carries_stm
    # rtol=0 on purpose: the default 1e-5 would be relative to a 1.8e6 m
    # radius, i.e. an 18 m tolerance, and the test would pass on a broken
    # propagator.
    assert np.allclose(arc.r[-1], circular_state[:3], rtol=0.0, atol=1e-3)
    assert np.allclose(arc.v[-1], circular_state[3:], rtol=0.0, atol=1e-6)


def test_stm_starts_at_identity(circular_state, tight) -> None:
    field = PointMassField(mu=MU_MOON)
    arc = propagate(field, circular_state, np.array([0.0, 60.0, 120.0]), 0,
                    tight, GradientConfig())
    assert arc.carries_stm
    assert np.allclose(arc.stm[0], np.eye(6), rtol=0.0, atol=1e-12)


def test_stm_matches_finite_difference_of_flow(circular_state, tight) -> None:
    """:math:`\\Phi` is the Jacobian of the flow. Verify it as one.

    Six perturbed propagations, differenced against six more, give the
    columns of :math:`\\partial\\mathbf x(t)/\\partial\\mathbf x(t_0)`
    directly.  A transposed or mis-blocked variational term fails here and
    passes every structural check, which is why this test exists.

    The :math:`J_2` field is used rather than a point mass so that the
    position--position block is not degenerate.
    """
    field = J2Field(mu=MU_MOON, reference_radius=R_MOON, j2=J2_MOON)
    span = 1800.0
    t_eval = np.array([0.0, span])
    # Symmetric perturbations: metres in position, mm/s in velocity, both
    # far above roundoff and far below the scale on which the flow curves.
    steps = np.array([1.0, 1.0, 1.0, 1.0e-3, 1.0e-3, 1.0e-3])

    arc = propagate(field, circular_state, t_eval, 2, tight, GradientConfig())
    phi_integrated = arc.stm[-1]

    phi_numeric = np.empty((6, 6))
    for j in range(6):
        bump = np.zeros(6)
        bump[j] = steps[j]
        plus = propagate(field, circular_state + bump, t_eval, 2, tight)
        minus = propagate(field, circular_state - bump, t_eval, 2, tight)
        end_plus = np.concatenate([plus.r[-1], plus.v[-1]])
        end_minus = np.concatenate([minus.r[-1], minus.v[-1]])
        phi_numeric[:, j] = (end_plus - end_minus) / (2.0 * steps[j])

    # Compare column by column: the columns have wildly different magnitudes
    # (a velocity column carries seconds), so a single absolute tolerance
    # would be vacuous for some and impossible for others.
    for j in range(6):
        scale = np.max(np.abs(phi_numeric[:, j]))
        assert np.allclose(phi_integrated[:, j], phi_numeric[:, j],
                           rtol=1e-6, atol=1e-8 * scale), f"column {j}"


def test_stm_stays_symplectic_over_an_orbit(circular_state, tight) -> None:
    """The integration diagnostic the campaign records once per arc."""
    field = J2Field(mu=MU_MOON, reference_radius=R_MOON, j2=J2_MOON)
    r0 = float(np.linalg.norm(circular_state[:3]))
    period = 2.0 * np.pi * np.sqrt(r0**3 / MU_MOON)
    t_eval = np.linspace(0.0, period, 25)

    arc = propagate(field, circular_state, t_eval, 2, tight, GradientConfig())
    speed0 = float(np.linalg.norm(circular_state[3:]))
    defect = symplectic_defect(arc.stm, r0, r0 / speed0)

    assert defect.shape == (25,)
    assert float(np.max(defect)) < 1.0e-9


def test_gradient_degree_is_recorded(circular_state, tight) -> None:
    """``None`` means "match the reference degree" and must be resolved, not
    stored as ``None``; Q13 turns on this number being auditable."""
    field = J2Field(mu=MU_MOON, reference_radius=R_MOON, j2=J2_MOON)
    t_eval = np.array([0.0, 60.0])

    matched = propagate(field, circular_state, t_eval, 2, tight,
                        GradientConfig(degree=None))
    explicit = propagate(field, circular_state, t_eval, 2, tight,
                         GradientConfig(degree=1))

    assert matched.gradient_degree == 2
    assert explicit.gradient_degree == 1
    assert propagate(field, circular_state, t_eval, 2,
                     tight).gradient_degree is None


def test_realized_rhs_count_is_reported(circular_state, tight) -> None:
    """Budget accounting needs realized work, not a nominal per-call figure."""
    field = PointMassField(mu=MU_MOON)
    arc = propagate(field, circular_state, np.linspace(0.0, 600.0, 6), 0, tight)
    assert arc.n_rhs > 0


# ---------------------------------------------------------------------------
# Input validation
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(("t_eval", "message"), [
    (np.array([60.0, 120.0]), "start at 0.0"),
    (np.array([0.0, 120.0, 60.0]), "strictly increasing"),
    (np.array([0.0]), "at least|>= 2|2 epochs"),
])
def test_bad_grid_is_rejected(circular_state, tight, t_eval, message) -> None:
    field = PointMassField(mu=MU_MOON)
    with pytest.raises(ValueError, match=message):
        propagate(field, circular_state, t_eval, 0, tight)


def test_bad_state_is_rejected(tight) -> None:
    field = PointMassField(mu=MU_MOON)
    with pytest.raises(ValueError, match=r"shape \(6,\)"):
        propagate(field, np.zeros(3), np.array([0.0, 60.0]), 0, tight)


def test_integration_failure_is_raised_not_absorbed(tight) -> None:
    """A collision course drives the solver into the singularity.

    Free-fall from rest at ``R_MOON`` reaches the origin in
    :math:`(\\pi/2)\\sqrt{r^3/2\\mu}\\approx 1150` s, so a span of 2000 s is
    past it with margin and the test does not depend on how long the solver
    thrashes.  The point is that the failure surfaces rather than being
    absorbed into a shorter arc or a looser retry.
    """
    field = PointMassField(mu=MU_MOON)
    radial_infall = np.array([R_MOON, 0.0, 0.0, 0.0, 0.0, 0.0])
    with pytest.raises(IntegrationError):
        propagate(field, radial_infall, np.array([0.0, 2.0e3]), 0, tight)


# ---------------------------------------------------------------------------
# Transport helpers
# ---------------------------------------------------------------------------


def test_velocity_transport_selects_the_acceleration_columns() -> None:
    rng = np.random.default_rng(3)
    phi = rng.normal(size=(4, 6, 6))
    b = np.vstack([np.zeros((3, 3)), np.eye(3)])
    assert np.array_equal(velocity_transport(phi), phi @ b)


def test_position_rows_selects_the_position_block() -> None:
    rng = np.random.default_rng(4)
    phi = rng.normal(size=(4, 6, 6))
    h_r = np.hstack([np.eye(3), np.zeros((3, 3))])
    assert np.array_equal(position_rows(phi), h_r @ phi)


def test_synthesis_count_is_explicit() -> None:
    assert estimate_syntheses_per_rhs(None) == 1
    assert estimate_syntheses_per_rhs(GradientConfig()) == 7


def test_work_factor_prices_the_gradient_degree() -> None:
    """Cost scales as N^2, so a cheaper gradient is cheaper than 6x.

    This is the number that prices the open question Q13: matching the
    reference degree costs 7x a plain propagation, halving it costs 2.5x.
    """
    assert estimate_rhs_work_factor(None, 300) == 1.0
    assert estimate_rhs_work_factor(GradientConfig(), 300) == pytest.approx(7.0)
    assert estimate_rhs_work_factor(GradientConfig(degree=150), 300) == \
        pytest.approx(2.5)
    assert estimate_rhs_work_factor(GradientConfig(degree=120), 600) == \
        pytest.approx(1.24)
    with pytest.raises(ValueError, match="positive"):
        estimate_rhs_work_factor(GradientConfig(), 0)
